#!/bin/bash
# -*- sh -*-

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	if [ -r /proc/stat ]; then
		echo yes
		exit 0
	else
		echo no
		exit 0
	fi
fi

if [ "$1" = "config" ]; then
    echo 'graph_title example'
    echo 'graph_args --base 1000 -r --lower-limit 0 --upper-limit 200'
    echo 'graph_vlabel %'
    echo 'graph_category custom'
    echo 'graph_info Example graph'
    echo 'sample.label sample'
    echo 'sample.info num of sample'
    exit 0
fi

echo -n "sample.value "
echo $(( RANDOM %= 200 ))
