#!/bin/sh

LYNX=/usr/bin/lynx

if [ "$1" = "config" ]; then
  echo 'graph_title Nikkei 225'
  echo 'graph_args --base 1000 -l 0'
  echo 'graph_vlabel Values'
  echo 'graph_info Nikkei 225'
  echo 'graph_category finance'

  echo 'price.label Nikkei 225'
  echo 'price.draw LINE1'
  echo 'price.info Nikkei 225'

  exit 0
fi

if [ "$1" = "autoconf" ]; then
  echo 'yes'
else
  echo -n "price.value "

  url="http://225225.jp/1jp/"
  HTML_RESULT=`$LYNX --source "${url}" |grep nkT1|grep '日経'|tr '>' ' '|tr '<' ' '|awk '{ print $8 }'|tr -d ',' |awk -F"." '{print $1}'`
  echo "$HTML_RESULT"
fi
