#!/bin/sh

test -d /usr/local/share/munin/plugins || sudo mkdir -p /usr/local/share/munin/plugins/
sudo cp ~/munin-plugins/process_monitoring /usr/local/share/munin/plugins/
test -L /etc/munin/plugins/process_monitoring || sudo ln -s /usr/local/share/munin/plugins/process_monitoring /etc/munin/plugins/process_monitoring
sudo vim /etc/sudoers

